name: Push&Pull workflow

on: [push, pull_request]

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up Python@3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint
    - name: Lint with pylint
      run: |
        python -m pylint --disable=all -e W0311 --jobs=0 --indent-string=' ' **/*.py
      

  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up Python@3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install pytest
    - name: Run Tests
      run: |
        python -m pytest -v
